from app.services.auth_service import (
    AuthenticationError,
    InactiveUserError,
    InsufficientPermissionsError,
    InvalidCredentialsError,
    TokenValidationError,
    authenticate_user,
    build_access_token,
    get_authenticated_user,
)
from app.services.exceptions import ConflictServiceError, NotFoundServiceError, ServiceError, ValidationServiceError
from app.services.ticket_service import (
    InactiveTicketUnitError,
    InvalidTicketUnitError,
    TicketNotFoundError,
    TicketPermissionError,
    create_ticket_record,
    get_ticket_detail,
    list_ticket_records,
)
from app.services.unit_service import (
    DuplicateUnitCodeError,
    UnitNotFoundError,
    create_unit_record,
    get_unit_or_404,
    list_unit_records,
    update_unit_record,
)
from app.services.user_service import (
    DuplicateUserEmailError,
    InvalidUserRoleConfigurationError,
    InvalidUserUnitError,
    UserNotFoundError,
    create_user_record,
    get_user_or_404,
    list_user_records,
    update_user_record,
)

__all__ = [
    "AuthenticationError",
    "ConflictServiceError",
    "create_ticket_record",
    "create_unit_record",
    "create_user_record",
    "DuplicateUnitCodeError",
    "DuplicateUserEmailError",
    "get_ticket_detail",
    "get_unit_or_404",
    "get_user_or_404",
    "InactiveTicketUnitError",
    "InactiveUserError",
    "InvalidTicketUnitError",
    "InvalidUserRoleConfigurationError",
    "InvalidUserUnitError",
    "InsufficientPermissionsError",
    "InvalidCredentialsError",
    "list_ticket_records",
    "list_unit_records",
    "list_user_records",
    "NotFoundServiceError",
    "ServiceError",
    "TokenValidationError",
    "TicketNotFoundError",
    "TicketPermissionError",
    "UnitNotFoundError",
    "update_unit_record",
    "update_user_record",
    "UserNotFoundError",
    "ValidationServiceError",
    "authenticate_user",
    "build_access_token",
    "get_authenticated_user",
]
